# Default values for armadaserver.
ingressHostNames: [localhost]
image:
  repository: gresearch/armada-server
  tag: 
replicas: 1
pulsarInit: false
postgres:
  dbname: postgres
  sslmode: false
pulsar:
  url: 
  armadaInit:
    # -- Pulsar image
    image:
      repository: richgross/pulsar
      tag: 2.11.0
    # -- Pulsar Broker host
    brokerHost: pulsar-broker.armada.svc.cluster.local
    # -- Protocol used for connecting to Pulsar Broker host (either `http` or `https`)
    protocol: http
    # -- Pulsar admin (REST) port
    adminPort: 8080
    # -- Pulsar application port
    port: 6650
redis:
  db: 0  
